/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Chip8()

        when:
        def result = lib.load_rom("/Users/ruimaranhao/ist/chip8/PONG")

        then:
        result == true
    }
}
